server:
    port: 8080

spring:
    config:
        import: optional:file:.env
    datasource:
        url: "jdbc:mysql://localhost:3306/newdb"
        driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:}
        username: "root"
        password: "020304"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB